### ISSUE TITLE
3.2.1: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [FactoryBoy/factory_boy#1016]
#### Description
Looks like documentation build fails with latest sphinx

#### To Reproduce
`sphinx-build -n -T -b man docs build/sphinx/man`

Here is the output
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.1.3
making output directory... done
loading intersphinx inventory from https://docs.python.org/objects.inv...
loading intersphinx inventory from https://docs.djangoproject.com/en/dev/_objects/...
loading intersphinx inventory from https://docs.sqlalchemy.org/en/latest/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
intersphinx inventory has moved: https://docs.sqlalchemy.org/en/latest/objects.inv -> https://docs.sqlalchemy.org/en/20/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 11 added, 0 changed, 0 removed
reading sources... [  9%] changelog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1170, in indent
    elements = self.block_quote(indented, line_offset)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1187, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1276, in bullet
    new_line_offset, blank_finish = self.nested_list_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2535, in bullet
    listitem, blank_finish = self.list_item(match.end())
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1295, in list_item
    self.nested_parse(indented, input_offset=line_offset,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2799, in text
    paragraph, literalnext = self.paragraph(lines, startline)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 416, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 425, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 649, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 792, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 889, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
TypeError: not all arguments converted during string formatting

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
TypeError: not all arguments converted during string formatting
The full traceback has been saved in /tmp/sphinx-err-_uabbztw.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.13
asgiref                       3.5.2
Babel                         2.12.1
backports.zoneinfo            0.2.1
build                         0.10.0
charset-normalizer            3.1.0
click                         8.1.3
distro                        1.8.0
Django                        4.1.7
docutils                      0.19
exceptiongroup                1.0.0
Faker                         18.4.0
Flask                         2.2.2
Flask-SQLAlchemy              3.0.3
gpg                           1.19.0
greenlet                      1.1.3
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.5.1
iniconfig                     2.0.0
installer                     0.7.0
itsdangerous                  2.1.2
Jinja2                        3.1.2
libcomps                      0.1.19
MarkupSafe                    2.1.2
packaging                     23.1
pluggy                        1.0.0
Pygments                      2.15.1
pyproject_hooks               1.0.0
pytest                        7.3.1
python-dateutil               2.8.2
pytz                          2023.2
requests                      2.28.2
setuptools                    67.6.1
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2.dev20230415
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20230415
sphinxcontrib-qthelp          1.0.3.dev20230415
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    2.0.10
sqlparse                      0.4.2
tomli                         2.0.1
typing_extensions             4.5.0
urllib3                       1.26.15
Werkzeug                      2.2.3
wheel                         0.40.0
zipp                          3.15.0
```
</details>

**Comment by francoisfreitag** [comment]
I would recommend the following procedure, which works for me :tm::
```sh
$ pip install -e '.[doc]'
$ cd docs/
$ make man
```

**Comment by kloczek** [comment]
> I would recommend the following procedure, which works for me ™️:
>
> ```shell
> $ pip install -e '.[doc]'
> $ cd docs/
> $ make man
> ```

in `[doc]` are liosted `sphinx, `sphinxcontrib-spelling` and `sphinx-rtd-theme`. Last two are not used in docs/conf.py.

Just have look closer on the docs/conf py and git repo.
https://github.com/FactoryBoy/factory_boy/commit/92816251872848524d247fb3d7e65abe7cbe7151 that commit is not part of the 3.2.1 and it fixes documentation build issue.

**Comment by kloczek** [comment]
After apply 92816251 it works
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.0
making output directory... done
WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
loading intersphinx inventory from https://docs.python.org/objects.inv...
loading intersphinx inventory from https://docs.djangoproject.com/en/dev/_objects/...
loading intersphinx inventory from https://docs.sqlalchemy.org/en/latest/objects.inv...
intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
intersphinx inventory has moved: https://docs.sqlalchemy.org/en/latest/objects.inv -> https://docs.sqlalchemy.org/en/20/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 11 added, 0 changed, 0 removed
reading sources... [100%] reference
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-factory-boy.3 { introduction reference orms recipes fuzzy examples internals changelog credits ideas } /home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/introduction.rst:107: WARNING: py:meth reference target not found: factory.@sequence
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/introduction.rst:145: WARNING: py:meth reference target not found: factory.@lazy_attribute
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/introduction.rst:179: WARNING: py:meth reference target not found: factory.@lazy_attribute
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:206: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:216: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:226: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:231: WARNING: py:obj reference target not found: strategy
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:235: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:244: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:599: WARNING: py:obj reference target not found: strategy
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:637: WARNING: py:class reference target not found: file
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:835: WARNING: py:meth reference target not found: LazyAttribute.lazy_attribute
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:868: WARNING: py:class reference target not found: builder.Resolver
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:1127: WARNING: py:attr reference target not found: factory.SubFactory.factory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:1334: WARNING: py:attr reference target not found: builder.Resolver.factory_parent
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:1788: WARNING: py:attr reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2008: WARNING: py:mod reference target not found: factory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2016: WARNING: py:class reference target not found: factory.base.Factory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2024: WARNING: py:obj reference target not found: klass
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2024: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2022: WARNING: py:class reference target not found: class
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2038: WARNING: py:obj reference target not found: klass
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2038: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2036: WARNING: py:class reference target not found: class
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2052: WARNING: py:obj reference target not found: klass
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2052: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2050: WARNING: py:class reference target not found: class
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2066: WARNING: py:obj reference target not found: klass
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2066: WARNING: py:obj reference target not found: strategy
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2066: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2064: WARNING: py:class reference target not found: class
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2081: WARNING: py:obj reference target not found: klass
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2081: WARNING: py:obj reference target not found: size
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2079: WARNING: py:class reference target not found: class
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2100: WARNING: py:mod reference target not found: factory.random
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/reference.rst:2116: WARNING: py:meth reference target not found: random.seed
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:121: WARNING: py:class reference target not found: file
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:121: WARNING: py:class reference target not found: func
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:154: WARNING: py:class reference target not found: file
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:154: WARNING: py:class reference target not found: func
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:270: WARNING: py:attr reference target not found: associated class <factory.FactoryOptions.model
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:270: WARNING: py:class reference target not found: mongoengine.EmbeddedDocument
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:270: WARNING: py:meth reference target not found: MongoEngineFactory.create
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:322: WARNING: py:meth reference target not found: sqlalchemy.orm.session.Session.add
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:327: WARNING: py:class reference target not found: factory.base.FactoryOptions
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:342: WARNING: py:meth reference target not found: sqlalchemy.orm.session.Session.flush
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:343: WARNING: py:meth reference target not found: sqlalchemy.orm.session.Session.commit
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:351: WARNING: py:meth reference target not found: sqlalchemy.orm.query.Query.one_or_none
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:351: WARNING: py:meth reference target not found: sqlalchemy.orm.session.Session.add
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/orms.rst:459: WARNING: py:meth reference target not found: sqlalchemy.orm.scoping.scoped_session.remove
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/recipes.rst:90: WARNING: py:class reference target not found: UserFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/recipes.rst:102: WARNING: py:meth reference target not found: factory.Factory._generate
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/recipes.rst:213: WARNING: py:class reference target not found: RelatedFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/recipes.rst:213: WARNING: py:class reference target not found: RelatedFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/fuzzy.rst:364: WARNING: py:obj reference target not found: factory.random.randgen
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/fuzzy.rst:364: WARNING: py:meth reference target not found: get_random_state
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/examples.rst:80: WARNING: py:class reference target not found: Account
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/examples.rst:80: WARNING: py:class reference target not found: Profile
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/internals.rst:56: WARNING: py:meth reference target not found: Factory.__call__
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/internals.rst:60: WARNING: py:meth reference target not found: Factory._generate
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/internals.rst:62: WARNING: py:meth reference target not found: Factory._generate_batch`
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/internals.rst:64: WARNING: py:meth reference target not found: Factory._generate
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/internals.rst:84: WARNING: py:meth reference target not found: FactoryOptions.instantiate
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:17: WARNING: py:meth reference target not found: factory.alchemy.SQLAlchemyModelFactory._save
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:17: WARNING: py:meth reference target not found: factory.alchemy.SQLAlchemyModelFactory._get_or_create
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:103: WARNING: py:attr reference target not found: factory.Factory.model
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:105: WARNING: py:meth reference target not found: get_random_state
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:110: WARNING: py:class reference target not found: factory.declarations.SubFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:128: WARNING: py:attr reference target not found: factory.fuzzy.FuzzyChoice.getter
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:130: WARNING: py:meth reference target not found: factory.faker.Faker.generate
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:132: WARNING: py:class reference target not found: factory.faker.Faker
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:154: WARNING: py:class reference target not found: factory.declarations.ParameteredAttribute
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:169: WARNING: py:class reference target not found: factory.PostGenerationDeclaration
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:291: WARNING: py:func reference target not found: django.apps.apps.get_model
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:292: WARNING: py:meth reference target not found: mogo.model.Model.new
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:401: WARNING: py:attr reference target not found: factory.Factory.FACTORY_FOR
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:402: WARNING: py:attr reference target not found: factory.Factory.ABSTRACT_FACTORY
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:403: WARNING: py:attr reference target not found: factory.Factory.FACTORY_STRATEGY
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:404: WARNING: py:attr reference target not found: factory.Factory.FACTORY_ARG_PARAMETERS
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:405: WARNING: py:attr reference target not found: factory.Factory.FACTORY_HIDDEN_ARGS
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:409: WARNING: py:attr reference target not found: factory.django.DjangoModelFactory.FACTORY_DJANGO_GET_OR_CREATE
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:413: WARNING: py:attr reference target not found: factory.alchemy.SQLAlchemyModelFactory.FACTORY_SESSION
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:435: WARNING: py:class reference target not found: mongoengine.EmbeddedDocument
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:454: WARNING: py:mod reference target not found: factory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:475: WARNING: py:class reference target not found: factory.Factory.ABSTRACT_FACTORY
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:475: WARNING: py:class reference target not found: factory.Factory.FACTORY_FOR
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:498: WARNING: py:attr reference target not found: factory.builder.Resolver.factory_parent
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:498: WARNING: py:class reference target not found: factory.builder.Resolver
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:501: WARNING: py:mod reference target not found: factory.django
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:501: WARNING: py:mod reference target not found: factory.mogo
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:530: WARNING: py:attr reference target not found: factory.django.DjangoModelFactory.FACTORY_DJANGO_GET_OR_CREATE
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:541: WARNING: py:attr reference target not found: factory.django.DjangoModelFactory.FACTORY_DJANGO_GET_OR_CREATE
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:554: WARNING: py:attr reference target not found: factory.Sequence.type
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:555: WARNING: py:attr reference target not found: factory.Factory.FACTORY_HIDDEN_ARGS
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:557: WARNING: py:attr reference target not found: factory.django.DjangoModelFactory.FACTORY_DJANGO_GET_OR_CREATE
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:566: WARNING: py:class reference target not found: factory.InfiniteIterator
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:566: WARNING: py:func reference target not found: factory.infinite_iterator
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:567: WARNING: py:class reference target not found: factory.CircularSubFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:571: WARNING: py:meth reference target not found: factory.Factory.set_building_function
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:571: WARNING: py:meth reference target not found: factory.Factory.set_creation_function
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:594: WARNING: py:attr reference target not found: factory.Factory.FACTORY_ARG_PARAMETERS
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:596: WARNING: py:attr reference target not found: factory.Factory.FACTORY_FOR
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:617: WARNING: py:class reference target not found: factory.InfiniteIterator
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:618: WARNING: py:class reference target not found: factory.CircularSubFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:622: WARNING: py:meth reference target not found: factory.Factory.set_creation_function
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:622: WARNING: py:meth reference target not found: factory.Factory.set_building_function
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:624: WARNING: py:attr reference target not found: factory.Factory.FACTORY_FOR
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:661: WARNING: py:class reference target not found: factory.CircularSubFactory
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:671: WARNING: py:class reference target not found: factory.PostGenerationDeclaration
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:705: WARNING: py:class reference target not found: factory.InfiniteIterator
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:728: WARNING: py:class reference target not found: factory.ContainerAttribute
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:738: WARNING: py:attr reference target not found: factory.Factory.FACTORY_FOR
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:751: WARNING: py:data reference target not found: factory.MOGO_BUILD
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/changelog.rst:753: WARNING: py:attr reference target not found: factory.Factory.ABSTRACT_FACTORY
/home/tkloczko/rpmbuild/BUILD/factory_boy-3.2.1/docs/ideas.rst:7: WARNING: py:class reference target not found: Factory
done
build succeeded, 116 warnings.
```
Nitpic warnings have been alreadfy reported in https://github.com/FactoryBoy/factory_boy/issues/929
Here is more good examples how to fix those warnings
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/sqlalchemy/sqlalchemy/commit/5e88e6e8

BTW https://github.com/FactoryBoy/factory_boy/compare/3.2.1...master shows +100 commits since last release.
Do you have any pnas to release new version soon? 🤔

**Comment by francoisfreitag** [comment]
> in [doc] are liosted sphinx, sphinxcontrib-spellingandsphinx-rtd-theme`. Last two are not used in docs/conf.py.

Both are used. `make spelling` instruments sphinx-spelling, while the rtd theme is used to theme the HTML documentation.

> https://github.com/FactoryBoy/factory_boy/commit/92816251872848524d247fb3d7e65abe7cbe7151 that commit is not part of the 3.2.1 and it fixes documentation build issue.

I’m the author of that commit. I had forgotten about it. The merge back of 3.2.1 to master was missed. https://github.com/FactoryBoy/factory_boy/pull/1012 offers to fix that.

**Comment by francoisfreitag** [comment]
> BTW https://github.com/FactoryBoy/factory_boy/compare/3.2.1...master shows +100 commits since last release.

We had a release blocker, that has been solved recently. A release will likely come in the next months.

**Comment by kloczek** [comment]
> We had a release blocker, that has been solved recently. A release will likely come in the next months.

👍 👀
