### ISSUE TITLE
Instances of DjangoModelFactory .build() method, try to save the object with foreign objects

### ISSUE THREAD

**Issue by braiam** [FactoryBoy/factory_boy#1023]
#### Description
When using the build strategy, as the documentation says "The ‘build’ strategy is used when an instance should be created, but not persisted to any datastore". I would expect that if I do not pass a create/save for any of the related objects. Passing None isn't an option if the related object has other relationships. Here's the factory definitions:

```python
from factory.django import DjangoModelFactory
import factory.fuzzy

import random

from manager import models
from manager import forms

from psycopg2.extras import NumericRange


class ContactCommonFactory(DjangoModelFactory):
    class Meta:
        model = models.Contact

    given_name = factory.Faker('first_name')
    last_name = factory.Faker('last_name')
    email = factory.Faker('email')
    phone_number = factory.Faker('phone_number')
    authorized_warehouse = factory.SubFactory(
        '..WarehouseCommonFactory')

    @factory.sequence
    def cedula(n):
        a = n // 10000
        b = (n * 10000000) % 10000
        c = n % 10000
        return '%03d-%07d-%01d' % (a, b, c)

class WarehouseCommonFactory(DjangoModelFactory):
    class Meta:
        model = models.Warehouse

    name = factory.Faker('name')
    primary_contact = factory.SubFactory(
        ContactCommonFactory)
    can_send = True
    can_recieve = True

    @factory.post_generation
    def primary_contact(self, create, extracted, **kwargs):
        ContactCommonFactory(authorized_warehouse=self)

class TransactionFactory(DjangoModelFactory):
    class Meta:
        model = models.Transactions

    recieving_warehouse = factory.SubFactory(
        WarehouseCommonFactory)
    sending_warehouse = factory.SubFactory(
        WarehouseCommonFactory)
    recieving_contact = factory.SubFactory(
        ContactCommonFactory,
        authorized_warehouse=factory.SelfAttribute(
            '..recieving_warehouse'))
    sending_contact = factory.SubFactory(
        ContactCommonFactory,
        authorized_warehouse=factory.SelfAttribute(
            '..sending_warehouse'))
    started_by = sending_contact

    current_status = models.Transactions.TransactionStatus.IN_PROCESS
```

#### To Reproduce

```python
>>> import factories
>>> factories.TransactionFactory.build()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/factory/base.py", line 511, in build
    return cls._generate(enums.BUILD_STRATEGY, kwargs)
  File "/usr/lib/python3/dist-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/usr/lib/python3/dist-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 258, in build
    step.resolve(pre)
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 199, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 344, in __getattr__
    value = value.evaluate_pre(
  File "/usr/lib/python3/dist-packages/factory/declarations.py", line 48, in evaluate_pre
    return self.evaluate(instance, step, context)
  File "/usr/lib/python3/dist-packages/factory/declarations.py", line 395, in evaluate
    return step.recurse(subfactory, extra, force_sequence=force_sequence)
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 216, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 271, in build
    postgen_results[declaration_name] = declaration.declaration.evaluate_post(
  File "/usr/lib/python3/dist-packages/factory/declarations.py", line 592, in evaluate_post
    return self.call(instance, step, postgen_context)
  File "/usr/lib/python3/dist-packages/factory/declarations.py", line 623, in call
    return self.function(
  File "/home/braiam/src/cert_mng/manager/factories.py", line 43, in primary_contact
    ContactCommonFactory(authorized_warehouse=self)
  File "/usr/lib/python3/dist-packages/factory/base.py", line 40, in __call__
    return cls.create(**kwargs)
  File "/usr/lib/python3/dist-packages/factory/base.py", line 528, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/lib/python3/dist-packages/factory/django.py", line 117, in _generate
    return super()._generate(strategy, params)
  File "/usr/lib/python3/dist-packages/factory/base.py", line 465, in _generate
    return step.build()
  File "/usr/lib/python3/dist-packages/factory/builder.py", line 262, in build
    instance = self.factory_meta.instantiate(
  File "/usr/lib/python3/dist-packages/factory/base.py", line 317, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/factory/django.py", line 166, in _create
    return manager.create(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 695, in save
    self._prepare_related_fields_for_save(operation_name='save')
  File "/usr/lib/python3/dist-packages/django/db/models/base.py", line 945, in _prepare_related_fields_for_save
    raise ValueError(
ValueError: save() prohibited to prevent data loss due to unsaved related object 'authorized_warehouse'.
```

I expect that either it doesn't need to create the related objects, uses some that is already created, or that it doesn't try to save.

**Comment by rbarrois** [comment]
The issue lies in the code of your `@factory.post_generation` argument: you're receiving a `create` flag, which should be taken into account for deciding whether to build or create the related instance.

The [example in the reference documentation](https://factoryboy.readthedocs.io/en/stable/reference.html#factory.post_generation) shows how to handle that case:

```python
@factory.post_generation
def primary_contact(self, create, extracted, **kwargs):
  if not create:
    return  # We could "build" a contact, but without a way to link it into the object that would be useless
  ContactCommonFactory(authorized_warehouse=self)
```
