### ISSUE TITLE
pip install factory_boy error on python3.3

### ISSUE THREAD

**Issue by guillaumevincent** [FactoryBoy/factory_boy#118]
I'm on FreeBSD 9.1-RELEASE-p7 with python3.3 running on a virtualenv
**pip install factory_boy** return UnicodeDecode Error

```
(.env)# pip install factory_boy
Downloading/unpacking factory-boy
  Downloading factory_boy-2.2.1.tar.gz (71kB): 71kB downloaded
  Running setup.py egg_info for package factory-boy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/cdp/.env/lib/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1018: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/cdp/.env/lib/python3.3/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1018: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/cdp/.env/build/factory-boy
Storing complete log in /root/.pip/pip.log
```

**Am I doing anything wrong ?**

**Comment by edouard-lopez** [comment]
I used the following command on a `Debian GNU/Linux 7.8 (wheezy)`

    # rebuild locale
    dpkg-reconfigure locales
    # set default (need to logout, log back)
    update-locale LC_ALL=fr_FR.utf8
    # for current session
    export LC_ALL=fr_FR.UTF-8
