### ISSUE TITLE
Error when a SubFactory contains image field

### ISSUE THREAD

**Issue by naglalakk** [FactoryBoy/factory_boy#338]
Hi. I'm getting an error when I try to save a factory which contains a SubFactory with an image field. These are my factories

```
class ImageFactory(factory.django.DjangoModelFactory):
    image = factory.Sequence(
        lambda n: random.choice([
            'mock/images/mock1.jpg',
            'mock/images/mock2.jpg',
            'mock/images/mock3.jpg'
        ])
    )
    notes = factory.Sequence(lambda n: fake.text())

    class Meta:
        model = 'photogenic.Image'

class AlbumImageFactory(factory.django.DjangoModelFactory):
    album = factory.SubFactory(AlbumFactory)
    image = factory.SubFactory(ImageFactory)

    class Meta:
        model = 'photogenic.AlbumImage'
```

What is strange is that this error does not occur when saving an ImageFactory instance.
Example

```
image = ImageFactory() # fine
image.image.url
'/media/mock/images/mock3.jpg'
```

When trying to save an AlbumImageFactory instance I get this error

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 69, in __call__
    return cls.create(**kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 622, in create
    attrs = cls.attributes(create=True, extra=kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 453, in attributes
    force_sequence=force_sequence,
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/containers.py", line 324, in build
    return stub.__fill__()
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/containers.py", line 83, in __fill__
    res[attr] = getattr(self, attr)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/containers.py", line 108, in __getattr__
    val = val.evaluate(self, self.__containers)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/containers.py", line 227, in evaluate
    containers=containers,
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/declarations.py", line 324, in evaluate
    return self.generate(sequence, obj, create, defaults)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/declarations.py", line 412, in generate
    return subfactory.simple_generate(create, **params)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 709, in simple_generate
    return cls.generate(strategy, **kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 676, in generate
    return action(**kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 623, in create
    return cls._generate(True, attrs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 548, in _generate
    obj = cls._prepare(create, **attrs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/base.py", line 523, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/factory/django.py", line 181, in _create
    return manager.create(*args, **kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1053, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1006, in as_sql
    for obj in self.query.objs
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1006, in <listcomp>
    for obj in self.query.objs
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1005, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 955, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/Users/Donna/Code/K0TT/repos/django_packages/photogenic/venv/lib/python3.5/site-packages/django/db/models/fields/files.py", line 290, in pre_save
    if file and not file._committed:
AttributeError: 'Image' object has no attribute '_committed'
```

### Versions
Django == 1.10.5
factory-boy == 2.8.1

**Comment by rbarrois** [comment]
Django has an unusual behavior with images; you should look at ``factory.django.ImageField`` which has been specifically designed for this.

Could you check with it?

**Comment by naglalakk** [comment]
@rbarrois you are correct. This is what I ended up using. The factory.django.ImageField includes everything I need, I was just unaware of it at the time. For me this solved the problem so if you want you can go ahead and close this issue.
