### ISSUE TITLE
Can't test model with m2m field without invoking m2m field - Django

### ISSUE THREAD

**Issue by neighlyd** [FactoryBoy/factory_boy#414]
I have several models that include optional Many-To-Many fields in Django. When running factory_boy tests, I get an iterator error when I attempt to run tests that don't address the Many-To-Many fields (through RelatedFactory - which has poor and confusing documentation), even though I'm not invoking these fields in any way, shape, or form.

```python
#models.py - simplified; I excluded a bunch of the fields and inherited foreign key models because they don't matter here.

class Person(models.Model):
    name = models.CharField(max_length=250)
    village = models.ForeignKey(Village)
    case_roles = models.ManyToMany(Role, through="Litigant", related_name="case_roles")

class Case(models.Model):
    summary = models.TextField()
    session = models.ForeignKey(Session)
    case_type = models.ForeignKey(CaseType)
    verdict = models.ForeignKey(Verdict)
    litigants = models.ManyToManyField(Person, through="Litigant", related_name="litigants")

class Litigant(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    role = models.ForeignKey(Role)
    notes = models.TextField()
```

```python
#test.py - again, simplified

class CaseFactory(factory.DjangoModelFactory):
    class Meta:
        model = Case
    
    summary = factory.Faker('paragraph')
    session = factory.SubFactory(SessionFactory)
    case_type = factory.SubFactory(CaseTypeFactory)
    verdict = factory.SubFactory(VerdictFactory)

class PersonFactory(factory.DjangoModelFactory):
    class Meta:
        model = Person

    name = factory.Faker('first_name')
    village = factory.SubFactory(VillageFactory)
    notes = factory.Faker('paragraph')

class LitigantFactory(factory.DjangoModelFactory):
    class Meta:
        model = Litigant

    person = factory.SubFactory(PersonFactory)
    case = factory.SubFactory(CaseFactory)
    role = factory.SubFactory(RoleFactory)
    notes = factory.Faker('paragraph')
```
If I try to create a CaseFactory, I get the following error:

```
Traceback (most recent call last):
  File "/vagrant/medievalpeasants/peasantlegaldb/tests.py", line 316, in test_case_creation
    s = SessionFactory.create()
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 363, in __getattr__
    extra=declaration.context,
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/declarations.py", line 306, in evaluate
    return self.generate(step, defaults)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/declarations.py", line 395, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 363, in __getattr__
    extra=declaration.context,
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/declarations.py", line 306, in evaluate
    return self.generate(step, defaults)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/declarations.py", line 395, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/builder.py", line 363, in __getattr__
    extra=declaration.context,
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/declarations.py", line 179, in evaluate
    value = next(iter(self.iterator))
  File "/home/vagrant/.virtualenvs/medievaldb/lib/python3.4/site-packages/factory/utils.py", line 136, in __iter__
    value = next(self.iterator)
StopIteration

```

However, if I comment out the ManyToMany field in the Case Class, the test runs fine.

Why would a non-required field in a model be required in an unrelated test?

**Comment by levic** [comment]
I think your simplifications in the above are hiding something that is the real cause. I just pasted the following into a local app:

```
import factory
from django.db import models

class Verdict(models.Model):
    pass
class CaseType(models.Model):
    pass
class Session(models.Model):
    pass
class Role(models.Model):
    pass
class Village(models.Model):
    pass

class Person(models.Model):
    name = models.CharField(max_length=250)
    village = models.ForeignKey(Village)
    case_roles = models.ManyToManyField(Role, through="Litigant", related_name="case_roles")

class Case(models.Model):
    summary = models.TextField()
    session = models.ForeignKey(Session)
    case_type = models.ForeignKey(CaseType)
    verdict = models.ForeignKey(Verdict)
    litigants = models.ManyToManyField(Person, through="Litigant", related_name="litigants")

class Litigant(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    role = models.ForeignKey(Role)
    notes = models.TextField()



class VillageFactory(factory.DjangoModelFactory):
    class Meta:
        model = Village
class SessionFactory(factory.DjangoModelFactory):
    class Meta:
        model = Session
class CaseTypeFactory(factory.DjangoModelFactory):
    class Meta:
        model = CaseType
class VerdictFactory(factory.DjangoModelFactory):
    class Meta:
        model = Verdict
class RoleFactory(factory.DjangoModelFactory):
    class Meta:
        model = Role

class CaseFactory(factory.DjangoModelFactory):
    class Meta:
        model = Case

    summary = factory.Faker('paragraph')
    session = factory.SubFactory(SessionFactory)
    case_type = factory.SubFactory(CaseTypeFactory)
    verdict = factory.SubFactory(VerdictFactory)


class PersonFactory(factory.DjangoModelFactory):
    class Meta:
        model = Person

    name = factory.Faker('first_name')
    village = factory.SubFactory(VillageFactory)
    notes = factory.Faker('paragraph')


class LitigantFactory(factory.DjangoModelFactory):
    class Meta:
        model = Litigant

    person = factory.SubFactory(PersonFactory)
    case = factory.SubFactory(CaseFactory)
    role = factory.SubFactory(RoleFactory)
    notes = factory.Faker('paragraph')
```

the following code works inside a test:
```
    def test414(self):
        models.CaseFactory.build()
        models.CaseFactory.create()

        models.SessionFactory.build()
        models.SessionFactory.create()
```

Note also that the top of your stack trace is a `SessionFactory`, not a `CaseFactory`.

I'm using django 1.11, python 3.6, factory boy `master`

**Comment by neighlyd** [comment]
Well, it seems that I'm just an idiot... It looks like the problem was in an implementation of factory.iterator and not the manytomany. I am not sure why removing the manytomany field would change the error message, though.

I apologize for bothering you and wasting your time. Though, your comment did help me track down my error.

**Comment by jeffwidman** [comment]
Thanks for chiming in @levic
