### ISSUE TITLE
'Options' object has no attribute 'pre_declarations'

### ISSUE THREAD

**Issue by AuHau** [FactoryBoy/factory_boy#437]
I am trying to make work tests on one of our projects and I am running into weird error which I am not sure how to debug. Could you please point me to right direction?

Django version: 1.10.8
Python version: 3.6.3
FactoryBoy version: latest

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/src/app/dj/apps/job/tests/views.py", line 36, in test_job_history
    driver = self._create_driver()
  File "/usr/src/app/dj/apps/job/tests/views.py", line 586, in _create_driver
    return DriverFactory(*args, **kwargs)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/builder.py", line 363, in __getattr__
    extra=declaration.context,
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/declarations.py", line 306, in evaluate
    return self.generate(step, defaults)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/declarations.py", line 395, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/usr/src/app/var/ve/lib/python3.6/site-packages/factory/builder.py", line 256, in build
    base_pre=self.factory_meta.pre_declarations,
AttributeError: 'Options' object has no attribute 'pre_declarations'
```

The factory is rather simple:
```
class DriverFactory(factory.django.DjangoModelFactory):
    bank_account = factory.SubFactory('profiles.tests.models.factories.BankAccount')

    first_name = factory.Sequence(lambda n: 'John{0}'.format(n))
    last_name = factory.Sequence(lambda n: 'Doe{0}'.format(n))
    phone = '+412123123123'

    user = factory.SubFactory('profiles.tests.models.factories.UserFactory')
    address = factory.SubFactory('profiles.tests.models.factories.AddressFactory')

    class Meta:
        model = Driver
```

**Comment by AuHau** [comment]
Hmm so stupid of me :-/ The `bank_account` sub factory should be named `BankAccountFactory`.

I would propose to do some validation if the SubFactory exists and if not to throw some reasonable exception with helpful message and not `AttributeError: 'Options' object has no attribute 'pre_declarations'` ;-)
