### ISSUE TITLE
SelfAttributes Fail When Called Through PostGeneration functions

### ISSUE THREAD

**Issue by marky1991** [FactoryBoy/factory_boy#446]
I have a simplified set of factory definitions below. This code successfully generates a workorderkit with factory_boy 2.6.1 but fails with 2.9.2. I'm wondering if this is a bug or if it worked unintentionally before and this is the intended behavior. (If it is the intended behavior, do you have any suggestions on achieving this behavior now?)

The whole example django project:  https://bitbucket.org/marky1991/factory-test/ .

import factory
from factory.declarations import SubFactory, SelfAttribute
from factory.fuzzy import FuzzyText, FuzzyChoice
from factory_test_app import models

class ItemFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.Item

    barcode = factory.fuzzy.FuzzyText(length=10)

class OrderHdrFactory(factory.DjangoModelFactory):
    order_nbr = factory.fuzzy.FuzzyText(length=20)
    class Meta:
        model = models.OrderHdr

    @factory.post_generation
    def order_dtls(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted is not None:
            for order_dtl in extracted:
                order_dtl.order = self
                author.save()
            return
        for _ in range(5):
            OrderDtlFactory(order=self,
                            **kwargs)

class WorkOrderKitFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.WorkOrderKit
    
    work_order_nbr = factory.fuzzy.FuzzyText(length=20)
    item = SubFactory(ItemFactory)
    sales_order = SubFactory(OrderHdrFactory,
                             order_dtls__item=SelfAttribute("..item"))

class OrderDtlFactory(factory.DjangoModelFactory):
    class Meta:
        model = models.OrderDtl

    order = SubFactory(OrderHdrFactory,
                       order_dtls=[])
    item = SubFactory(ItemFactory)

**Comment by flaeppe** [comment]
I've run into a similar issue when upgrading to `>=2.9.0`. Although my issue appeared when utilising `factory.Trait` together with `post_generation` which seemed to have some internal implementation changed to now use `factory.SelfAttribute`(this is my suspicion at least).

This problem sounds to (might) have been introduced in my case when:

> Add :class:`factory.Maybe`, which chooses among two possible declarations based on another field's value (powers the :class:`~factory.Trait` feature).

I'm currently using `2.7.0`, where the following snippet **passes**(also on `2.8.x` versions), it fails however on `>=2.9.0`:

_I'm also running Python 3.5 if that would happen to make any difference._

```python
import factory
from django.test import TestCase


class MyGroupFactory(factory.django.DjangoModelFactory):

    class Meta:
        model = 'auth.Group'
        django_get_or_create = ('name',)

    class Params:
        admin = factory.Trait(name='admins')


class MyUserFactory(factory.django.DjangoModelFactory):
    email = factory.Sequence(lambda n: '%03d@email.com' % n)

    class Meta:
        model = 'core.UserProfile'

    class Params:
        admin = factory.Trait(groups__admin=True)

    @factory.post_generation
    def groups(self, create, extracted, **kwargs):
        if not create:
            return

        if extracted:
            self.groups.add(*extracted)
        elif kwargs:
            self.groups.add(MyGroupFactory(**kwargs))


class UserTests(TestCase):
    def test_failing_factory(self):
        MyUserFactory(admin=True)
```

I get a very similar traceback to @marky1991, hence I suspect that we've encountered the same bug here.

Traceback with `>=2.9.0`:
```
Traceback (most recent call last):
  File "/app/tests.py", line 43, in test_failing_factory
    MyUserFactory(admin=True)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/usr/local/lib/python3.5/site-packages/factory/builder.py", line 296, in build
    context=postgen_context,
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 570, in call
    instance, create, context.value, **context.extra)
  File "/app/tests.py", line 38, in groups
    self.groups.add(MyGroupFactory(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python3.5/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/usr/local/lib/python3.5/site-packages/factory/builder.py", line 275, in build
    step.resolve(pre)
  File "/usr/local/lib/python3.5/site-packages/factory/builder.py", line 224, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/usr/local/lib/python3.5/site-packages/factory/builder.py", line 366, in __getattr__
    extra=declaration.context,
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 440, in evaluate
    choice = self.decider.evaluate(instance=instance, step=step, extra={})
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 142, in evaluate
    return deepgetattr(target, self.attribute_name, self.default)
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 104, in deepgetattr
    return getattr(obj, name)
  File "/usr/local/lib/python3.5/site-packages/factory/builder.py", line 366, in __getattr__
    extra=declaration.context,
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 440, in evaluate
    choice = self.decider.evaluate(instance=instance, step=step, extra={})
  File "/usr/local/lib/python3.5/site-packages/factory/declarations.py", line 137, in evaluate
    target = step.chain[self.depth - 1]
IndexError: tuple index out of range
```

**Comment by marky1991** [comment]
@rbarrois Do you have any comments on the intended design? I'd be willing to work on this issue if I knew what, if anything, you want to do about it. (but if nothing, what workaround you suggest)

**Comment by rbarrois** [comment]
Hey, sorry for the awfully late reply :/

I think this was actually the same issue as #466 — which I just fixed in the 2.11.0 release.

Could you check if the issue still occurs for you?

**Comment by flaeppe** [comment]
@rbarrois running with `>=2.11.0` the issue is resolved. 👍 (at least for my case above)

**Comment by AlecRosenbaum** [comment]
I'm running into the same exact issue that @Subaku described above. Is there a workaround?

**Comment by rbarrois** [comment]
@AlecRosenbaum could you share some code on the kind of issue you're seeing?

In @Subaku example code, what happens is that the overridden `install` value is designed to be passed into the `extracted` field of the `post_generation` method; and resolved within the context of that method's parameters.

In other words, there is an intermediate level where parameters for `def install()` are computed (required for cases where more parameters are provided to that declaration, where each parameter might use values from other parameters).
When calling `SelfAttribute('..thing2')`, the `..` part goes up a level to `FooFactory`, not to `BooFactory`; using `factory.SelfAttribute('...thing2')` should work.

However, passing in a pre-generation declaration (`SelfAttribute` here) to shadow a post-generation declaration makes the factories much harder to read, and could fail in unexpected ways; I recommend designing the factory differently, for instance playing with `class Params` for passing in parameters.

**Comment by AlecRosenbaum** [comment]
@rbarrois Huh, ok so adding an extra `.` on the `SelfAttribute` works starting in version `2.11.0` but doesn't work in lower versions. Thanks!

The situation I am setting up is a little different from the previous example, so I'll put some runnable code (with pytest) here documenting the use case. I'm not sure how I would use `Params`, since the code has to run after creation. Please let me know if I'm wrong about `Params` or if you have any suggestions on how to set it up cleaner.

<details><summary>Example Scenario</summary>
<p>

```python
import factory

# ==============
# --- Models ---
# ==============

RELATIONSHIPS = set()


def rel_key(_from, to, type):
    return "{}::{}::{}".format(_from, to, type)


class User(object):
    def __init__(self, name):
        self.name = name

    def add_to_organization(self, org):
        # some mumbo-jumbo here
        RELATIONSHIPS.add(rel_key(_from=self.name, to=org.name, type="member"))

    def member_of_organization(self, org):
        key = rel_key(_from=self.name, to=org.name, type="member")
        return key in RELATIONSHIPS


class Organization(object):
    def __init__(self, name):
        self.name = name


class Event(object):
    def __init__(self, organization, user):
        self.organization = organization
        self.user = user


# =================
# --- Factories ---
# =================


class UserFactory(factory.Factory):
    name = "Johnny Smith"

    class Meta:
        model = User

    @factory.post_generation
    def organization(user_inst, create, extracted, **kwargs):
        if create and extracted:
            user_inst.add_to_organization(extracted)


class OrganizationFactory(factory.Factory):
    name = "The Smith Organization"

    class Meta:
        model = Organization


class EventFactory(factory.Factory):
    organization = OrganizationFactory()
    user = factory.SubFactory(
        UserFactory, organization=factory.SelfAttribute("...organization")
    )

    class Meta:
        model = Event


# ====================
# --- Example Test ---
# ====================


def test_event():
    my_event = EventFactory()

    assert my_event.organization
    assert my_event.user
    assert my_event.user.member_of_organization(my_event.organization)
```

</p>
</details>
