### ISSUE TITLE
Factory classes accept only model attribute names as variables

### ISSUE THREAD

**Issue by cho-leukeleu** [FactoryBoy/factory_boy#448]
Hi and thanks for this nice faking tool !

I ran into a strange behaviour today. Apparently all variables used within a factory class need to exist as an attribute in the model it's faking.

Initializing `treatment_state` this way:
```python
class ClientFactory(UserProfileFactory):
    class Meta:
        model = Client
        django_get_or_create = ('user',)

    treatment_state = factory.Faker('random_element', elements=[st for st, _ in TREATMENT_STATES])
```
will raise this error
```
Traceback (most recent call last):
  File "/Users/christineho/Documents/dev.vm1/project/current_instance/project/tests/test_selenium/test_flow.py", line 30, in setUp
    user__first_name='JanSmit'
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/django.py", line 163, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/factory/django.py", line 154, in _get_or_create
    instance, _created = manager.get_or_create(*args, **key_fields)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/django/db/models/query.py", line 459, in get_or_create
    lookup, params = self._extract_model_params(defaults, **kwargs)
  File "/Users/christineho/.virtualenvs/project/lib/python2.7/site-packages/django/db/models/query.py", line 534, in _extract_model_params
    "', '".join(sorted(invalid_params)),
FieldError: Invalid field name(s) for model Client: 'st'.
```
while this would work fine
```
treatment_state = factory.Faker('random_element', elements=[treatment_state for treatment_state, _ in TREATMENT_STATES])
```

Let me know if you need more info.

**Comment by rbarrois** [comment]
This is a scope bleeding issue with Python 2 (see #6).

When you write:
```python
class Foo(object):
  x = [y ** 2 for y in range(8)]
```

Then you'll see that ``Foo`` has a ``y`` attribute defined.

factory_boy has some provisions against this - basically, if you name the temporary variable ``_st`` instead of ``st``, it won't be included in the final call to the model.
Another option would be to add it to the [``Meta.exclude``](http://factoryboy.readthedocs.io/en/latest/reference.html#factory.FactoryOptions.exclude) parameter to skip it.

**Comment by rbarrois** [comment]
Looks like this solved your issue; please reopen the issue otherwise ;)
