### ISSUE TITLE
release 2.10.0 has broken passing conditional kwargs to post_generation methods

### ISSUE THREAD

**Issue by dlobue** [FactoryBoy/factory_boy#466]
This issue is easiesr to show than explain. Here's a simplified version of my code:

```python
    import factory
    from factory.fuzzy import FuzzyText


    class CopyTarget(object):
        def __init__(self, label, plain_m2m=None):
            self.label = label
            self.plain_m2m = plain_m2m or []


    class Other(object):
        def __init__(self, label):
            self.label = label


    class BaseFactory(factory.Factory):
        label = FuzzyText()


    class OtherFactory(BaseFactory):
        class Meta:
            model = Other


    class CopyTargetFactory(BaseFactory):
        class Meta:
            model = CopyTarget

        class Params:
            empty = factory.Trait(
                plain_m2m=None,
                plain_m2m__num=0,
            )

        plain_m2m__num = 3

        @factory.post_generation
        def plain_m2m(self, create, extracted, num=0, **kwargs):
            if not create:
                # Simple build, do nothing.
                return

            if extracted is not None:
                if not isinstance(extracted, Iterable):
                    extracted = [extracted]
                self.plain_m2m.extend(*extracted)
            elif num:
                self.plain_m2m.extend(*(OtherFactory()
                                     for _ in xrange(num)))



    if __name__ == '__main__':
        value = CopyTargetFactory()
```

What's happening is in 2.10.0 is xrange is not receiving an integer like it expects. Here's the traceback:

    Traceback (most recent call last):
      File "/root/docs/notes/gist/factoryboy_maybe_broke_postgen.py", line 55, in <module>
        value = CopyTargetFactory()
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/base.py", line 46, in __call__
        return cls.create(**kwargs)
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/base.py", line 563, in create
        return cls._generate(enums.CREATE_STRATEGY, kwargs)
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/base.py", line 500, in _generate
        return step.build()
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/builder.py", line 293, in build
        context=postgen_context,
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/declarations.py", line 472, in call
        context=context,
      File "/root/.pyenv/versions/frontend/lib/python2.7/site-packages/factory/declarations.py", line 610, in call
        instance, create, context.value, **context.extra)
      File "/root/docs/notes/gist/factoryboy_maybe_broke_postgen.py", line 50, in plain_m2m
        for _ in xrange(num)))
    TypeError: an integer is required

For some reason, `num` is an instance of `Maybe`. Here's the repr of it: `Maybe(<SelfAttribute(u'empty', default=False)>, yes=0, no=3)`. I've used this code successfully in factory-boy version 2.7.0 and 2.9.2.

**Comment by rbarrois** [comment]
Indeed, that's a bug. Basically, the use of the ``Trait`` turns the ``plain_m2m__num=3`` declaration into a ``Maybe(decider, yes, no)`` declaration.

And that declaration is not resolved before being passed to the ``post_generation`` declaration.
