### ISSUE TITLE
Latest Doc version is always 0.1.0

### ISSUE THREAD

**Issue by tonial** [FactoryBoy/factory_boy#704]
#### Description
The latest doc version is 0.1.0 : see here https://factoryboy.readthedocs.io/_/downloads/en/latest/pdf/ 

This is probably a consequence of https://github.com/FactoryBoy/factory_boy/commit/93bbd0317092c8e804d039ed60413f4b75fd7e77
I guess we only need to fix this piece of code : https://github.com/FactoryBoy/factory_boy/blob/79161b0409842b5fc8a43d5844669f233403e14c/docs/conf.py#L63-L73

**Comment by francoisfreitag** [comment]
Yes, that was indeed a regression, thanks for spotting it!
Fixed by merging https://github.com/FactoryBoy/factory_boy/pull/676.

**Comment by rbarrois** [comment]
Builds keep failing, the #676 fix wasn't sufficient:

```python
python /home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/checkouts/latest/docs/conf.py", line 17, in <module>
    import factory
ModuleNotFoundError: No module named 'factory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/checkouts/latest/docs/conf.py", line 17, in <module>
    import factory
ModuleNotFoundError: No module named 'factory'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/factoryboy/checkouts/latest/docs/conf.py", line 17, in <module>
    import factory
ModuleNotFoundError: No module named 'factory' 
```

@francoisfreitag could you look into that?
