### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Dumisani2** [FactoryBoy/factory_boy#943]
Hi 
kindly assist, everytime I'm trying to run this command: **superset db upgrade**, it produces the error below:

```
(superset-env) dumisani_mthalane@Dumisani-0LVTE88:~$ superset db upgrade
INFO:root:logging was configured successfully
/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/flask_caching/__init__.py:119: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Failed to create app
Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 59, in create_app
    app_initializer.init_app()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 430, in init_app_in_ctx
    self.configure_url_map_converters()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 514, in configure_url_map_converters
    from superset.utils.url_map_converters import RegexConverter
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/utils/url_map_converters.py", line 19, in <module>
    from superset.models.tags import ObjectTypes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/__init__.py", line 17, in <module>
    from . import core, datasource_access_request, schedules, sql_lab, user_attributes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/core.py", line 54, in <module>
    from superset import app, db_engine_specs, is_feature_enabled, security_manager
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs/__init__.py", line 40, in <module>
    for (_, name, _) in pkgutil.iter_modules([Path(__file__).parent]):  # type: ignore
  File "/usr/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
ERROR:superset.app:Failed to create app
Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 59, in create_app
    app_initializer.init_app()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 430, in init_app_in_ctx
    self.configure_url_map_converters()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 514, in configure_url_map_converters
    from superset.utils.url_map_converters import RegexConverter
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/utils/url_map_converters.py", line 19, in <module>
    from superset.models.tags import ObjectTypes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/__init__.py", line 17, in <module>
    from . import core, datasource_access_request, schedules, sql_lab, user_attributes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/core.py", line 54, in <module>
    from superset import app, db_engine_specs, is_feature_enabled, security_manager
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs/__init__.py", line 40, in <module>
    for (_, name, _) in pkgutil.iter_modules([Path(__file__).parent]):  # type: ignore
  File "/usr/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dumisani_mthalane/superset-env/bin/superset", line 21, in <module>
    superset()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/flask/cli.py", line 579, in main
    return super().main(*args, **kwargs)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/flask/cli.py", line 426, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/flask/cli.py", line 382, in load_app
    app = self.create_app()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 66, in create_app
    raise ex
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 59, in create_app
    app_initializer.init_app()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 469, in init_app
    self.init_app_in_ctx()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 430, in init_app_in_ctx
    self.configure_url_map_converters()
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/app.py", line 514, in configure_url_map_converters
    from superset.utils.url_map_converters import RegexConverter
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/utils/url_map_converters.py", line 19, in <module>
    from superset.models.tags import ObjectTypes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/__init__.py", line 17, in <module>
    from . import core, datasource_access_request, schedules, sql_lab, user_attributes
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/models/core.py", line 54, in <module>
    from superset import app, db_engine_specs, is_feature_enabled, security_manager
  File "/home/dumisani_mthalane/superset-env/lib/python3.10/site-packages/superset/db_engine_specs/__init__.py", line 40, in <module>
    for (_, name, _) in pkgutil.iter_modules([Path(__file__).parent]):  # type: ignore
  File "/usr/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Comment by Dumisani2** [comment]
I'm running Python 3.10.4 on ubuntu for windows

**Comment by francoisfreitag** [comment]
Hi!
It looks like a `PosixPath` is passed to a module that expects `str`s. Could it be that the superset library does not handle pathlib paths?
What makes you think this error is related to FactoryBoy?

**Comment by francoisfreitag** [comment]
This place is to discuss FactoryBoy issues, a library that generates Python data.
I would recommend searching https://stackoverflow.com/questions/tagged/superset, and if you do not find an answer, maybe ask your question there.

**Comment by francoisfreitag** [comment]
This place is to discuss FactoryBoy issues, a library that generates data (usually for tests).
I would recommend searching https://stackoverflow.com/questions/tagged/superset, and if you do not find an answer, maybe ask your question there.
